apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paytm
  name: paytm-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paytm
  template:
    metadata:
      labels:
        app: paytm
    spec:
      containers:
      - name: cont1
        image: summu97/paytmmovies:v1
        ports:
          - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: paytm
  ports:
    - port: 80
      targetPort: 80
